POST http://localhost:8000/api/v1/user/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "teste1",
    "name": "Teste 1",
    "password": "1234",
    "email": "teste1@example.com"
}

###

GET http://localhost:8000/api/v1/user/list HTTP/1.1

###

POST http://localhost:8000/api/v1/user/login/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 6a4b840bbefcb840c49710af1af4058971eddb38

{
  "username": "teste1",
  "password": "1234"
}

###

DELETE http://localhost:8000/api/v1/user/delete/3 HTTP/1.1

